name: brew_app
description: Testing flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.3
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.0.0
  intl: ^0.18.0
  logger: ^2.0.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
