// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCMj0aL4aNatOMzf8S9eSHp_riY7Xf8I',
    appId: '1:520176794717:web:7de57878f9ac0128eba1b4',
    messagingSenderId: '520176794717',
    projectId: 'brewapp-1',
    authDomain: 'brewapp-1.firebaseapp.com',
    storageBucket: 'brewapp-1.appspot.com',
    measurementId: 'G-TV2LL65F60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcmuebpihW1Mwc03h7nHQQBlfzCCq_2M',
    appId: '1:520176794717:android:f5067705dd43f925eba1b4',
    messagingSenderId: '520176794717',
    projectId: 'brewapp-1',
    storageBucket: 'brewapp-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywdQJPL1jSUV-uICkBGakBwAxzxuVwE0',
    appId: '1:520176794717:ios:1918dd554d964cb8eba1b4',
    messagingSenderId: '520176794717',
    projectId: 'brewapp-1',
    storageBucket: 'brewapp-1.appspot.com',
    iosClientId: '520176794717-k2vc646tnl271hvb06fmhn30dmj4qu1u.apps.googleusercontent.com',
    iosBundleId: 'abc',
  );
}
